citation_manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('citations.urls', namespace='citations')),
]

citations/urls.py
"""Defines URL patterns for citaions."""

from django.conf.urls import url

from . import views

urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),

    # Show all citations
    url(r'^citations/$', views.citations, name='citations'),

    # page for adding new citations
    url(r'^new_citation/$', views.new_citation, name='new_citation'),

    # Page for editing a citation
    url(r'^edit_citation/(?P<citation_id>\d+)/$', views.edit_citation,
        name='edit_citation'),
]

users/urls.py
"""Defines URL patterns for users."""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # Login page
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),

    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),

    # Registration page
    url(r'^register/$', views.register, name='register'),
]

citations/models.py
from django.db import models
from django.contrib.auth.models import User

class Citation(models.Model):
    """A citation created by a user"""
    title = models.CharField(max_length=200)
    link = models.CharField(max_length=200)
    note = models.TextField()
    owner = models.ForeignKey(User)

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.title) > 50:
            return self.title[:50] + "..."
        else:
            return self.title

users/models.py
from django.db import models

# Create your models here.

citations/forms.py
from django import forms

from .models import Citation

class CitationForm(forms.ModelForm):
    class Meta:
        model = Citation
        fields = ['title','link','note']
        labels = {'title': 'Title',
                  'link': 'URL',
                  'note': 'Note'
                 }

citations/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Citation
from .forms import CitationForm

def index(request):
    """The home page for Citation Manager."""
    return render(request, 'citations/index.html')

@login_required
def citations(request):
    """Show all citations."""
    citations = Citation.objects.filter(owner=request.user)
    context = {'citations': citations}
    return render(request, 'citations/citations.html', context)

@login_required
def new_citation(request):
    """Add a new citation."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = CitationForm()
    else:
        # POST data submitted; process data.
        form = CitationForm(request.POST)
        if form.is_valid():
            new_citation = form.save(commit=False)
            new_citation.owner = request.user
            new_citation.save()
            return HttpResponseRedirect(reverse('citations:citations'))

    context = {'form': form}
    return render(request, 'citations/new_citation.html', context)

@login_required
def edit_citation(request, citation_id):
    """Edit an existing citation."""
    citation = Citation.objects.get(id=citation_id)
    if citation.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with current entry.
        form = CitationForm(instance=citation)
    else:
        # POST data submitted; process data.
        form = CitationForm(instance=citation, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('citations:citations'))

    context = {'citation': citation, 'form': form}
    return render(request, 'citations/edit_citation.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('citations:index'))

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process submitted form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('citations:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

citations/templates/citations/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X_UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Citation Manager</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
              <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
          </button>
          <a class="navbar-brand" href="{% url 'citations:index' %}">
            Citation Manager</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'citations:citations' %}">
                Citations</a>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>{{ user.username }}</a></li>
              <li><a href="{% url 'users:logout' %}">Log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">Register</a></li>
              <li><a href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
          </ul>
        </div>

      </div>
    </nav>

    <br />

    <div class="container">
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div>
  </body>
</html>

citations/templates/citations/citations.html
{% extends "citations/base.html" %}

{% block header %}
  <h1>Citations</h1>
{% endblock header %}

{% block content %}

  {% for citation in citations %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ citation.title }}
          <small>
            <a href="{% url 'citations:edit_citation'  citation.id %}">
              Edit entry</a>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        <a href="{{ citation.link }}">{{citation.link }}</a>:
        {{ citation.note }}
      </div>
    </div>
  {% empty %}
    You have no citations
  {% endfor %}

  <h3><a href="{% url 'citations:new_citation' %}">Add a new citation</a></h3>

{% endblock content %}

citations/templates/citations/edit_citation.html
{% extends 'citations/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Edit citation:</h2>
{% endblock header %}

{% block content %}

  <form action="{% url 'citations:edit_citation' citation.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}

  </form>

{% endblock content %}

citations/templates/citations/index.html
{% extends "citations/base.html" %}

{% block header %}
  <div class="jumbotron">
    <h1>Keep track of citations.</h1>
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to keep
    track of citations for a project, including title, link and notes.
  </h2>
{% endblock content %}

citations/templates/citations/new_citation.html
{% extends "citations/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new citation:</h2>
{% endblock header %}

{% block content %}

  <form action="{% url 'citations:new_citation' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Add citation</button>
    {% endbuttons %}

  </form>

{% endblock content %}

users/templates/users/login.html
{% extends "citations/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Log in</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'citations:index' %}" />
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends "citations/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Register to get your own private citation list</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Register</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'citations:index' %}" />
  </form>

{% endblock content %}